### ISSUE TITLE
gfx-backend-metal build.rs compilation error for target x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by clemarescx** [amethyst/space-menace#9] opened 2019-07-10 07:54 UTC
Just FYI, compiling on Windows 10 with Rust 1.36, target x86_64-pc-windows-msvc, both stable and nightly, gives the following error:
```powershell
error: failed to run custom build command for `gfx-backend-metal v0.2.1`

Caused by:
  process didn't exit successfully: `C:\Work\GitRepos\code-name-dune\target\debug\build\gfx-backend-metal-206d35fc40fc6342\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'unsupported target x86_64-pc-windows-msvc', C:\Users\YourMum\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-metal-0.2.1\build.rs:17:9
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Program Files\Rust\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.29\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650\/src\libstd\panicking.rs:200
   4: std::panicking::default_hook
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650\/src\libstd\panicking.rs:214
   5: std::panicking::rust_panic_with_hook
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650\/src\libstd\panicking.rs:477
   6: std::panicking::continue_panic_fmt
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650\/src\libstd\panicking.rs:384
   7: std::panicking::begin_panic_fmt
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650\/src\libstd\panicking.rs:339
   8: build_script_build::main
             at .\build.rs:17
   9: std::rt::lang_start::{{closure}}<()>
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650\src\libstd\rt.rs:64
  10: std::rt::lang_start_internal::{{closure}}
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650\/src\libstd\rt.rs:49
  11: std::panicking::try::do_call<closure,i32>
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650\/src\libstd\panicking.rs:296
  12: panic_unwind::__rust_maybe_catch_panic
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650\/src\libpanic_unwind\lib.rs:82
  13: std::panicking::try
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650\/src\libstd\panicking.rs:275
  14: std::panic::catch_unwind
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650\/src\libstd\panic.rs:394
  15: std::rt::lang_start_internal
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650\/src\libstd\rt.rs:48
  16: std::rt::lang_start<()>
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650\src\libstd\rt.rs:64
  17: main
  18: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  19: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  20: BaseThreadInitThunk
  21: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Noah2610** [comment] 2019-07-12 19:15
I get the same error on Linux:
`unsupported target x86_64-unknown-linux-gnu`

Tried with Rust versions 1.34.0 (stable/nightly), 1.36.0 (stable), and 1.38.0 (nightly); all get the same error.

**Comment by zaethan** [comment] 2019-07-13 13:28
This project seems to be using apples "metal" graphics api as can be seen in the Cargo.toml file under [dependencies]
`amethyst = { git = "https://github.com/amethyst/amethyst", features = ["nightly", "metal", "json"] }`

Thus this project probably fails to build on anything but macos. To run this project on linux or windows, you probably have to replace "metal" in the Cargo.toml with "vulkan", which is a cross platform graphics api.

**Comment by krankur** [comment] 2019-07-14 17:52
@clemarescx @Noah2610 thanks for reporting this. As @zaethan mentioned, on Windows and Linux, instead of `metal`, the `vulkan` backend is used. Just edit the `amethyst` dependency features in `Cargo.toml` to include `vulkan` instead of `metal`.
```
amethyst = { git = "https://github.com/amethyst/amethyst", features = ["nightly", "vulkan", "json"] }
```
I have added this information to the README as well.
Let me know if you face the issue even after switching to `vulkan`.

**Comment by Noah2610** [comment] 2019-07-15 15:03
All works well with the change to `vulkan`! One more minor detail though:
You need to use `nightly` rust in order to run the game. Maybe this should be put into the README as well?

**Comment by krankur** [comment] 2019-07-15 18:16
@Noah2610 thanks for confirming. And yes, good point. I will add nightly Rust as a prerequisite to the README.

**Comment by krankur** [comment] 2019-07-15 18:19
Closing this issue as things are working fine as confirmed by @Noah2610 above.

**Closed by krankur** 2019-07-15 18:19 UTC
